-- ============================================
-- SEED: restore the 27 insurance/tax/notary services
-- ============================================
-- The public services page used to render this content from static i18n
-- keys + hardcoded icon components. That was replaced with a Supabase-backed
-- CRUD (src/views/admin/Service*.vue) but the table was never seeded, so the
-- public page currently reads an empty table and shows nothing.
--
-- This restores the original content into public.services, sourced directly
-- from src/i18n/es.json and src/i18n/en.json's "services.items.*" keys.
-- Icons were extracted from src/components/icons/*.vue into static files at
-- public/service-icons/<slug>.svg (no Supabase Storage upload needed for
-- these — they ship with the site).
--
-- Safe to run once. Skips rows whose slug already exists.

insert into public.services
  (slug, category, sub_category, active, icon_url, title_es, title_en, cover_es, cover_en, why_es, why_en, who_es, who_en, sort_order)
values
  ($q$auto$q$, $q$insurance$q$, $q$personal$q$, true, $q$/service-icons/auto.svg$q$, $q$Seguro de Auto$q$, $q$Auto Insurance$q$, $q$Responsabilidad civil, daños al vehículo, robo y gastos médicos.$q$, $q$Liability, vehicle damage, theft and medical expenses.$q$, $q$Es obligatorio por ley y protege tu patrimonio ante accidentes.$q$, $q$Required by law and protects your assets.$q$, $q$Conductores que desean circular legalmente y con tranquilidad.$q$, $q$Drivers.$q$, 0),
  ($q$life$q$, $q$insurance$q$, $q$personal$q$, true, $q$/service-icons/life.svg$q$, $q$Seguro de Vida$q$, $q$Life Insurance$q$, $q$Apoyo económico a tus beneficiarios en caso de fallecimiento.$q$, $q$Financial support for beneficiaries.$q$, $q$Protege el futuro financiero de tu familia.$q$, $q$Protects your family's future.$q$, $q$Personas con dependientes o responsabilidades financieras.$q$, $q$People with dependents.$q$, 1),
  ($q$health$q$, $q$insurance$q$, $q$personal$q$, true, $q$/service-icons/health.svg$q$, $q$Seguro de Salud$q$, $q$Health Insurance$q$, $q$Consultas médicas, hospitalización y medicamentos.$q$, $q$Medical care and hospitalization.$q$, $q$Reduce costos médicos inesperados.$q$, $q$Reduces unexpected medical costs.$q$, $q$Individuos y familias.$q$, $q$Individuals and families.$q$, 2),
  ($q$renters$q$, $q$insurance$q$, $q$personal$q$, true, $q$/service-icons/renters.svg$q$, $q$Seguro de Inquilino$q$, $q$Renters Insurance$q$, $q$Protección de pertenencias personales en propiedades rentadas.$q$, $q$Protection for personal belongings.$q$, $q$La póliza del propietario no cubre tus bienes.$q$, $q$Landlord insurance does not cover tenants.$q$, $q$Personas que rentan vivienda.$q$, $q$Renters.$q$, 3),
  ($q$home$q$, $q$insurance$q$, $q$personal$q$, true, $q$/service-icons/home.svg$q$, $q$Seguro de Casa$q$, $q$Home Insurance$q$, $q$Estructura, bienes y responsabilidad civil.$q$, $q$Structure, belongings and liability.$q$, $q$Protege la inversión más importante de tu vida.$q$, $q$Protects your most valuable investment.$q$, $q$Propietarios de viviendas.$q$, $q$Homeowners.$q$, 4),
  ($q$umbrella$q$, $q$insurance$q$, $q$personal$q$, true, $q$/service-icons/umbrella.svg$q$, $q$Seguro Umbrella$q$, $q$Umbrella Insurance$q$, $q$Cobertura adicional de responsabilidad civil.$q$, $q$Additional liability coverage.$q$, $q$Protege contra demandas de alto valor.$q$, $q$Protects against large lawsuits.$q$, $q$Personas con activos significativos.$q$, $q$High-asset individuals.$q$, 5),
  ($q$general-liability$q$, $q$insurance$q$, $q$commercial$q$, true, $q$/service-icons/general-liability.svg$q$, $q$General Liability$q$, $q$General Liability$q$, $q$Daños a terceros y lesiones corporales.$q$, $q$Third-party damages and injuries.$q$, $q$Protege tu negocio de demandas.$q$, $q$Protects your business.$q$, $q$Empresas y contratistas.$q$, $q$Businesses.$q$, 0),
  ($q$workers-comp$q$, $q$insurance$q$, $q$commercial$q$, true, $q$/service-icons/workers-comp.svg$q$, $q$Workers Compensation$q$, $q$Workers Compensation$q$, $q$Gastos médicos y salarios perdidos de empleados.$q$, $q$Employee medical expenses.$q$, $q$Es obligatorio por ley.$q$, $q$Legally required.$q$, $q$Negocios con empleados.$q$, $q$Employers.$q$, 1),
  ($q$commercial-auto$q$, $q$insurance$q$, $q$commercial$q$, true, $q$/service-icons/commercial-auto.svg$q$, $q$Auto Comercial$q$, $q$Commercial Auto$q$, $q$Vehículos usados para actividades comerciales.$q$, $q$Business vehicle coverage.$q$, $q$Las pólizas personales no cubren uso comercial.$q$, $q$Personal insurance does not apply.$q$, $q$Negocios con vehículos.$q$, $q$Companies.$q$, 2),
  ($q$employer-umbrella$q$, $q$insurance$q$, $q$commercial$q$, true, $q$/service-icons/employer-umbrella.svg$q$, $q$Umbrella Comercial$q$, $q$Commercial Umbrella$q$, $q$Cobertura extendida para negocios.$q$, $q$Extended liability coverage.$q$, $q$Evita pérdidas financieras graves.$q$, $q$Prevents major losses.$q$, $q$Empresas con alto riesgo.$q$, $q$High-risk businesses.$q$, 3),
  ($q$business-owners$q$, $q$insurance$q$, $q$commercial$q$, true, $q$/service-icons/business-owners.svg$q$, $q$Business Owners Policy (BOP)$q$, $q$Business Owners Policy$q$, $q$Responsabilidad y propiedad en una sola póliza.$q$, $q$Property and liability combined.$q$, $q$Más económico y completo.$q$, $q$Cost-effective coverage.$q$, $q$Pequeñas y medianas empresas.$q$, $q$Small businesses.$q$, 4),
  ($q$w2$q$, $q$taxes$q$, $q$personal$q$, true, $q$/service-icons/w2.svg$q$, $q$Declaración W-2$q$, $q$W-2 Tax Filing$q$, $q$Preparación de impuestos personales.$q$, $q$Personal tax preparation.$q$, $q$Evita errores y maximiza reembolsos.$q$, $q$Avoid mistakes.$q$, $q$Empleados.$q$, $q$Employees.$q$, 0),
  ($q$non-owned$q$, $q$taxes$q$, $q$personal$q$, true, $q$/service-icons/non-owned.svg$q$, $q$Contratistas Independientes bajo la forma 1099-NEC$q$, $q$Independent Contractors - Form 1099-NEC$q$, $q$Cálculo de ingresos, gastos deducibles y preparación del Schedule C para contratistas.$q$, $q$Calculation of income, deductible expenses, and Schedule C preparation for contractors.$q$, $q$Optimiza tus deducciones para pagar el mínimo impuesto legalmente permitido por el IRS.$q$, $q$Optimizes your deductions to pay the minimum tax legally allowed by the IRS.$q$, $q$Trabajadores independientes, freelancers y conductores de plataformas digitales.$q$, $q$Independent contractors, freelancers, and gig economy drivers.$q$, 1),
  ($q$local-liability$q$, $q$taxes$q$, $q$commercial$q$, true, $q$/service-icons/local-liability.svg$q$, $q$Impuestos LLC$q$, $q$LLC Taxes$q$, $q$Preparación de impuestos para Sociedades de Responsabilidad Limitada y reporte de ganancias$q$, $q$Tax preparation for Limited Liability Companies and profit reporting.$q$, $q$Mantiene a tu empresa en 'Good Standing' y evita auditorías o cierres administrativos.$q$, $q$Keeps your company in 'Good Standing' and avoids audits or administrative closures.$q$, $q$Dueños de pequeñas empresas registradas como LLC en cualquier estado.$q$, $q$Small business owners registered as an LLC in any state.$q$, 0),
  ($q$society$q$, $q$taxes$q$, $q$commercial$q$, true, $q$/service-icons/society.svg$q$, $q$Sociedades$q$, $q$Business Entities (or Corporations)$q$, $q$Cálculo, reporte y envío de los impuestos sobre las ventas recaudados a nivel estatal.$q$, $q$Calculation, reporting, and filing of sales taxes collected at the state level.$q$, $q$Es una responsabilidad fiduciaria; no reportarlo puede conllevar graves multas penales.$q$, $q$This is a fiduciary responsibility; failure to report can lead to severe criminal penalties and fines.$q$, $q$Negocios que venden productos físicos o servicios sujetos a impuestos estatales.$q$, $q$Businesses that sell physical products or services subject to state taxes.$q$, 1),
  ($q$corp$q$, $q$taxes$q$, $q$commercial$q$, true, $q$/service-icons/corp.svg$q$, $q$Corporaciones (S/C)$q$, $q$Corporations (S/C Corp)$q$, $q$Declaraciones complejas para estructuras corporativas con distribución de dividendos.$q$, $q$Complex tax returns for corporate structures with dividend distribution.$q$, $q$Permite una planeación fiscal avanzada para reducir la carga impositiva de los socios.$q$, $q$Allows for advanced tax planning to reduce the tax burden on shareholders.$q$, $q$Empresas con múltiples socios o que buscan una estructura fiscal más robusta.$q$, $q$Businesses with multiple partners or those seeking a more robust tax structure.$q$, 2),
  ($q$church$q$, $q$taxes$q$, $q$commercial$q$, true, $q$/service-icons/church.svg$q$, $q$Iglesias o Sin fines de Lucro$q$, $q$Churches or Non-Profits$q$, $q$Gestión de retenciones federales, estatales y pagos de desempleo para tus empleados.$q$, $q$Management of federal and state withholdings and unemployment payments for your employees.$q$, $q$Garantiza que el pago a tus trabajadores sea exacto y cumpla con todas las leyes laborales.$q$, $q$Ensures that payments to your workers are accurate and comply with all labor laws.$q$, $q$Cualquier dueño de negocio con empleados en nómina.$q$, $q$Any business owner with employees on payroll.$q$, 3),
  ($q$travel$q$, $q$notary$q$, $q$personal$q$, true, $q$/service-icons/travel.svg$q$, $q$Cartas para salir del País$q$, $q$Minor Travel Consent Letter$q$, $q$Documento notariado que autoriza el viaje de menores de edad solos o con terceros.$q$, $q$A notarized document authorizing a minor to travel alone or with a third party.$q$, $q$Es una exigencia de seguridad en aeropuertos y aduanas para prevenir el tráfico de menores.$q$, $q$Required for security at airports and by customs to help prevent child trafficking.$q$, $q$Padres que necesitan enviar a sus hijos de viaje por vacaciones o motivos familiares.$q$, $q$Parents who need to send their children on vacation or for family trips.$q$, 0),
  ($q$weddings$q$, $q$notary$q$, $q$personal$q$, true, $q$/service-icons/weddings.svg$q$, $q$Bodas$q$, $q$Civil Weddings$q$, $q$Oficiación de ceremonias civiles y procesamiento legal de la licencia de matrimonio.$q$, $q$Marriage officiation.$q$, $q$Formaliza el vínculo matrimonial de manera legal, rápida y con validez estatal.$q$, $q$Legal recognition.$q$, $q$Parejas que desean contraer matrimonio civil sin las largas esperas de una corte.$q$, $q$Couples.$q$, 1),
  ($q$apostille$q$, $q$notary$q$, $q$personal$q$, true, $q$/service-icons/apostille.svg$q$, $q$Apostillados$q$, $q$Apostille Services$q$, $q$Validación internacional de documentos.$q$, $q$International validation.$q$, $q$Requisito legal internacional.$q$, $q$Required abroad.$q$, $q$Personas con trámites internacionales.$q$, $q$International applicants.$q$, 2),
  ($q$certifications$q$, $q$notary$q$, $q$personal$q$, true, $q$/service-icons/certifications.svg$q$, $q$Certificaciones$q$, $q$Certified Copies$q$, $q$Validación de copias de documentos originales como títulos, actas o identificaciones.$q$, $q$Validation of copies of original documents such as degrees, certificates, or IDs.$q$, $q$Permite entregar una copia fiel del original con respaldo notarial para trámites oficiales.$q$, $q$Allows you to provide a true copy of the original with notarized support for official procedures.$q$, $q$Estudiantes o profesionales que aplican a trabajos o instituciones educativas.$q$, $q$Students or professionals applying to jobs or educational institutions.$q$, 3),
  ($q$legal-procedures$q$, $q$notary$q$, $q$personal$q$, true, $q$/service-icons/legal-procedures.svg$q$, $q$Poderes Legales$q$, $q$Power of Attorney$q$, $q$Autorización amplia para que un tercero administre bienes y realice actos legales en tu nombre.$q$, $q$Broad authorization for a third party to manage assets and perform legal acts on your behalf.$q$, $q$Permite que tus asuntos sigan funcionando si te encuentras fuera del país o incapacitado.$q$, $q$Ensures your affairs continue to operate if you are out of the country or incapacitated.$q$, $q$Personas que viajan por largo tiempo o necesitan representación legal absoluta.$q$, $q$Individuals traveling for long periods or those in need of absolute legal representation.$q$, 4),
  ($q$tlegal$q$, $q$notary$q$, $q$personal$q$, true, $q$/service-icons/tlegal.svg$q$, $q$Tutela Legal$q$, $q$Legal Guardianship$q$, $q$Documentación para la designación de guardianes legales para menores de edad o dependientes$q$, $q$Documentation for the appointment of legal guardians for minors or dependents.$q$, $q$Asegura que tus seres queridos queden bajo el cuidado de personas de tu total confianza.$q$, $q$Ensures your loved ones are placed under the care of individuals you fully trust.$q$, $q$Padres y tutores que desean dejar protegida la custodia de sus hijos ante cualquier eventualidad.$q$, $q$Parents and guardians who wish to protect the custody of their children in the event of any contingency.$q$, 5),
  ($q$legal-translation$q$, $q$notary$q$, $q$personal$q$, true, $q$/service-icons/legal-translation.svg$q$, $q$Traducción Legal$q$, $q$Legal Translation$q$, $q$Traducción profesional y certificada de documentos de todo tipo (Inglés/Español).$q$, $q$Professional, certified translation of documents of any kind (English/Spanish).$q$, $q$Garantiza que la traducción sea fiel al original y aceptada por USCIS o cortes legales.$q$, $q$Ensures the translation is faithful to the original and accepted by USCIS or legal courts.$q$, $q$Cualquier persona con documentos extranjeros que necesite presentarlos ante autoridades en EE.UU.$q$, $q$Anyone with foreign documents that need to be presented to authorities in the U.S.$q$, 6),
  ($q$accounting$q$, $q$notary$q$, $q$commercial$q$, true, $q$/service-icons/accounting.svg$q$, $q$Contabilidad$q$, $q$Bookkeeping & Accounting$q$, $q$Registro mensual de ingresos y egresos, conciliación bancaria y preparación de estados financieros.$q$, $q$Monthly recording of income and expenses, bank reconciliation, and preparation of financial statements.$q$, $q$Te permite conocer la salud real de tu negocio y estar preparado para la temporada de impuestos.$q$, $q$Allows you to know the real health of your business and be prepared for tax season.$q$, $q$Empresarios que desean mantener sus finanzas organizadas y tomar decisiones basadas en datos.$q$, $q$Business owners who want to keep their finances organized and make data-driven decisions.$q$, 0),
  ($q$companies$q$, $q$notary$q$, $q$commercial$q$, true, $q$/service-icons/companies.svg$q$, $q$Registración de Compañías$q$, $q$Business Registration$q$, $q$Registro oficial ante el Estado, obtención del número EIN y preparación de documentos operativos.$q$, $q$Official registration with the State, obtaining an EIN, and preparation of operating documents.$q$, $q$Formaliza tu emprendimiento, protege tu patrimonio personal y te permite abrir cuentas bancarias comerciales.$q$, $q$Formalizes your venture, protects your personal assets, and allows you to open business bank accounts.$q$, $q$Emprendedores que desean iniciar una LLC, Corporación o cualquier entidad legal en EE.UU.$q$, $q$Entrepreneurs looking to start an LLC, Corporation, or any legal entity in the USA.$q$, 1),
  ($q$rep-companies$q$, $q$notary$q$, $q$commercial$q$, true, $q$/service-icons/rep-companies.svg$q$, $q$Planillas de compañía$q$, $q$Payroll Services$q$, $q$Procesamiento de nómina, cálculo de retenciones federales/estatales y emisión de talones de pago.$q$, $q$Payroll processing, calculation of federal/state withholdings, and issuance of pay stubs.$q$, $q$Asegura que tus empleados reciban su pago a tiempo y que tu negocio cumpla con las leyes laborales.$q$, $q$Ensures your employees are paid on time and your business remains compliant with labor laws.$q$, $q$Dueños de negocios con empleados que buscan automatizar y legalizar sus pagos de nómina.$q$, $q$Business owners with employees looking to automate and legalize their payroll payments.$q$, 2)
on conflict (slug) do nothing;
